# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 281fb707335facaa2785bb6958e0e84289a0de74341699cc32636f520892a44d5a12f17537807a5beec79c4faaa83642f4c8765b04839777eb2b3ef504b56899

test:
  secret_key_base: cb4ac310ece19d75c91ba3038aadd8e48678ec33ae7bb11b0c24fd4747d6b6dfe72ff156dcecbb7e0c05ff50346a344636a99769c58bf480ab44868bdb57b3d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
